# Generated by Django 3.0.3 on 2020-03-31 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200331_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('can_check_all_borrowed_books', 'Check all borrowed books'),)},
        ),
    ]
