# Generated by Django 3.0.3 on 2020-04-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200408_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_update_create_delete_book', 'Access for update Book'),)},
        ),
    ]
